{% set name = "flask-multipass" %}
{% set version = "0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-Multipass-{{ version }}.tar.gz
  sha256: 6930bcd1abe079d571b852ab9d4a7b76f9c6ebcaadaf43f368013120e4a92d80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - authlib >=0.14.1,<=1.0.0a1
    - blinker
    - flask >=0.10.1
    - flask-wtf
    - python >=3.6
    - python-ldap >=3.3.1,<4.0
    - sqlalchemy

test:
  imports:
    - flask_multipass
    - flask_multipass.auth
    - flask_multipass.core
    - flask_multipass.data
    - flask_multipass.exceptions
    - flask_multipass.group
    - flask_multipass.identity
    - flask_multipass.util
    - flask_multipass.providers
    - flask_multipass.providers.authlib
    - flask_multipass.providers.ldap
    - flask_multipass.providers.ldap.exceptions
    - flask_multipass.providers.ldap.globals
    - flask_multipass.providers.ldap.operations
    - flask_multipass.providers.ldap.providers
    - flask_multipass.providers.ldap.util
    - flask_multipass.providers.shibboleth
    - flask_multipass.providers.sqlalchemy
    - flask_multipass.providers.static
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/indico/flask-multipass
  summary: A pluggable solution for multi-backend authentication with Flask
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
    - ThiefMaster
